version: '3'
services:
  backend:
    build: backend/
    command: python ./server.py
    networks:
      - backend
  server:
    build: server/
    networks:
      - backend
      - frontend
  client:
    build: client/
    command: python -u ./client.py
    depends_on:
      - server
    networks:
      - frontend
networks:
  frontend:
  backend: